/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f1f1f1",
        "surface-container-low": "#f3f3f3",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-container": "#00217a",
        "surface-container": "#eeeeee",
        "secondary-fixed-dim": "#b8c4ff",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-container": "#708cfd",
        primary: "#004ac6",
        "surface-container-lowest": "#ffffff",
        tertiary: "#46566c",
        "on-primary-fixed": "#00174b",
        "primary-container": "#2563eb",
        "on-secondary-fixed": "#001453",
        "on-error": "#ffffff",
        "surface-variant": "#e2e2e2",
        "on-error-container": "#93000a",
        "on-primary-container": "#eeefff",
        "surface-dim": "#dadada",
        "on-secondary-fixed-variant": "#173bab",
        surface: "#f9f9f9",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed-variant": "#38485d",
        secondary: "#3755c3",
        "surface-container-high": "#e8e8e8",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#0b1c30",
        "tertiary-fixed-dim": "#b7c8e1",
        "tertiary-container": "#5e6e85",
        "secondary-fixed": "#dde1ff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#e9f0ff",
        "on-surface-variant": "#434655",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f3131",
        outline: "#737686",
        "on-tertiary": "#ffffff",
        background: "#f9f9f9",
        "error-container": "#ffdad6",
        "surface-tint": "#0053db",
        "tertiary-fixed": "#d3e4fe",
        "on-background": "#1a1c1c",
        "inverse-primary": "#b4c5ff",
        "on-surface": "#1a1c1c",
        "surface-bright": "#f9f9f9",
        "outline-variant": "#c3c6d7",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: { "stack-md": "16px", "margin-desktop": "64px", unit: "4px", "margin-mobile": "20px", "stack-sm": "8px", "stack-lg": "32px", gutter: "24px" },
      fontFamily: {
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Source Serif 4", "serif"],
        "display-xl": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Source Serif 4", "serif"],
        "label-technical": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "code-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-technical": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
